# Generated by Django 2.2.15 on 2020-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('skill_ball_control', models.IntegerField()),
                ('movement_reactions', models.IntegerField()),
                ('mentality_composure', models.IntegerField()),
                ('gk_diving', models.IntegerField()),
                ('gk_handling', models.IntegerField()),
                ('gk_positioning', models.IntegerField()),
                ('gk_reflexes', models.IntegerField()),
                ('st', models.IntegerField()),
                ('cf', models.IntegerField()),
                ('cam', models.IntegerField()),
                ('rm', models.IntegerField()),
                ('cdm', models.IntegerField()),
                ('rwb', models.IntegerField()),
                ('cb', models.IntegerField()),
                ('rb', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
